service: line-bot

frameworkVersion: "=1.30.3"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: sls

functions:
  lineFacialDeviationValue:
    handler: line.webhook
    timeout: 30
    environment: ${file(./conf/conf.yml)}

    events:
      - http:
          path: line/webhook
          method: post
